---

- name: Setup the Git repo
  git:
       repo="{{git_repo}}"
       version="{{ git_branch }}"
       dest="{{ project_path }}"
  when: setup_git_repo is defined and setup_git_repo
  tags: git

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ application_path }}"
  tags: git
